insert into item(ITEM_ID, COEF, NAME) values (1,2.4,'Football')
insert into item(ITEM_ID, COEF, NAME) values (2,5.2,'Skiing')
insert into item(ITEM_ID, COEF, NAME) values (3,1.1,'Basketball')
insert into item(ITEM_ID, COEF, NAME) values (4,5.2,'Baseball')

insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Srbija','Serbia')
insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Engleska','England')
insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Nemačka','Germany')
insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Italija','Italy')
insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Španija','Spain')
insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Holandija','Netherlands')
insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Francuska','France')
insert into region(SER_TRANSLATION, EN_TRANSLATION) values ('Rusija','Russia')