package travelsafe.business.rules;

import travelsafe.model.*;

###

rule "Initial price"
salience 0
dialect "mvel"
    when
        $travelInsurance : TravelInsurance(price == null)
        $price : Price()
    then
        Double newTotalPrice = $price.getAmount();

        $travelInsurance.setTotalPrice(newTotalPrice);
        $travelInsurance.setPrice($price);
    end

rule "Initial price - already connected with price"
salience 0
dialect "mvel"
    when
        $travelInsurance : TravelInsurance(price != null)
    then
        Double newTotalPrice = $travelInsurance.getPrice().getAmount();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

rule "Travel insurance duratin - less than or equal five days"
salience -1
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice, $duration : getDuration() <= 5 , $numberOfPeople : numberOfPeople)
        $item : Item(name_en == "less_than_equal_five_duration")
    then
        Double newTotalPrice = $currentTotalPrice + $numberOfPeople*$duration*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

rule "Travel insurance duration - more than five"
salience -1
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice, $duration : getDuration() > 5, $numberOfPeople :numberOfPeople)
        $item : Item(name_en == "more_than_five_duration")
    then
        Double newTotalPrice = $currentTotalPrice + $numberOfPeople*$duration*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

###

rule "Travel insurance number of people - more than five"
salience -3
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice)
        $item : Item(name_en == "more_than_five_people")
    then
        Double newTotalPrice = $currentTotalPrice*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

rule "Travel insurance max amount - more than 1000$"
salience -4
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice, 10000 < maxAmount, $maxAmount : maxAmount)
        $item : Item(name_en == "more_than_10000_max_amount")
    then
        Double newTotalPrice = $currentTotalPrice*$maxAmount*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

rule "Home insurance surface area"
salience -5
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice)
        $homeInsurance : HomeInsurance($surfaceArea : surfaceArea, travelInsurance == $travelInsurance)
        $item : Item(name_en == "surface_area_hi")
    then
        Double newTotalPrice = $currentTotalPrice + $surfaceArea*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

rule "Home insurance age"
salience -6
dialect "mvel"
    when
        $travelInsurance :TravelInsurance($currentTotalPrice : totalPrice)
        $homeInsurance : HomeInsurance($age : age, travelInsurance == $travelInsurance)
        $item : Item(name_en == "age_hi")
    then
        Double newTotalPrice = $currentTotalPrice + $age*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

rule "Home insurance estimated value"
salience -6
dialect "mvel"
    when
        $travelInsurance :TravelInsurance($currentTotalPrice : totalPrice)
        $homeInsurance : HomeInsurance($estimatedValue : estimatedValue, travelInsurance == $travelInsurance)
        $item : Item(name_en == "estimated_value_hi")
    then
        Double newTotalPrice = $currentTotalPrice + $estimatedValue*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

rule "Home insurance protect of flood"
salience -6
dialect "mvel"
    when
        $travelInsurance :TravelInsurance($currentTotalPrice : totalPrice)
        $homeInsurance : HomeInsurance($estimatedValue : estimatedValue, travelInsurance == $travelInsurance)
        $item : Item(name_en == "flood_hi")
    then
        Double newTotalPrice = $currentTotalPrice + $estimatedValue*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

rule "Home insurance proterct of fire"
salience -6
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice)
        $homeInsurance : HomeInsurance($estimatedValue : estimatedValue, travelInsurance == $travelInsurance)
        $item : Item(name_en == "fire_hi")
    then
        Double newTotalPrice = $currentTotalPrice + $estimatedValue*$item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

###

rule "Car insurance TOWING_SERVICE"
salience -7
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice)
        $carPackage : CarPackage(offer == OfferType.TOWING_SERVICE)
        $item : Item(name_en == "towing_service_ci")
    then
        Double newTotalPrice = $currentTotalPrice + $item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

rule "Car insurance ALTERNATIVE_TRANSPORT"
salience -7
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice)
        $carPackage : CarPackage(offer == OfferType.ALTERNATIVE_TRANSPORT)
        $item : Item(name_en == "alternative_transport_ci")
    then
        Double newTotalPrice = $currentTotalPrice + $item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

rule "Car insurance HOTEL_ACCOMMODATION"
salience -7
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice)
        $carPackage : CarPackage(offer == OfferType.HOTEL_ACCOMMODATION)
        $item : Item(name_en == "hotel_accommodation_ci")
    then
        Double newTotalPrice = $currentTotalPrice + $item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end

rule "Car insurance REPAIR"
salience -7
dialect "mvel"
    when
        $travelInsurance : TravelInsurance($currentTotalPrice : totalPrice)
        $carPackage : CarPackage(offer == OfferType.REPAIR)
        $item : Item(name_en == "repair_ci")
    then
        Double newTotalPrice = $currentTotalPrice + $item.getCoef();

        $travelInsurance.setTotalPrice(newTotalPrice);
    end