package travelsafe.paypal;

import com.paypal.api.payments.*;
import com.paypal.base.rest.PayPalRESTException;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * Created by aloha on 23-Nov-16.
 */
@Service
public class PayPalService {


    /**
     * When user clicks to buy a product on our website
     * Flow:
     * 0. Call backend
     * 1. Create Payment object (set finish payment URLs, cost, description etc.)
     * 2. Ask PayPal to generate URL where user will be redirected so that he/she can confirm or cancel payment usig that Payment object
     * 3. Return that URL
     * 4. Redirect user to that URL
     *
     * @param cost how much user is charged
     * @param description description of payment
     * @param itemId id of an object that represents item (basket, or in our case it is TravelInsurance)
     * @param shipping cost of shipping
     * @return Link object - look for 'approval_url' - that is url where user should be redirected so he/she can
     *         confirm or cancel buying product - link is generated by PayPal
     * */
    public Links createPayment(long itemId, long cost, long shipping, String description) throws NullPointerException{


        // Set payment details
        Details details = new Details();
        details.setShipping(String.valueOf(shipping));
        details.setSubtotal(String.valueOf(cost));
        details.setTax("0");
        System.out.println(">>> DETAILS");

        // Payment amount
        Amount amount = new Amount();
        amount.setCurrency("USD");
        // Total must be equal to sum of shipping, tax and subtotal.
        amount.setTotal(String.valueOf(cost)+String.valueOf(shipping));
        amount.setDetails(details);
        System.out.println(">>> AMMOUNT");

        // Transaction information
        Transaction transaction = new Transaction();
        transaction.setAmount(amount);
        transaction.setDescription(description);
        System.out.println(">>> TRANSASCION");


        //------------------------------------
        // Items
        // TODO - home, car, etc
        /*
        Item item = new Item();
        item.setName("Ground Coffee 40 oz").setQuantity("1").setCurrency("USD").setPrice("5");
        ItemList itemList = new ItemList();
        List<Item> items = new ArrayList<Item>();
        items.add(item);
        itemList.setItems(items);

        transaction.setItemList(itemList);
        */
        //------------------------------------

        // Add transaction to a list
        List<Transaction> transactions = new ArrayList<>();
        transactions.add(transaction);

        // Add payer details
        Payer payer = new Payer();
        payer.setPaymentMethod("paypal");
        System.out.println(">>> PAYER");

        // Add payment details
        Payment payment = new Payment();
        payment.setIntent("sale");
        payment.setPayer(payer);
        payment.setTransactions(transactions);
        System.out.println(">>> PAYMENT");

        // Add redirect URLs
        RedirectUrls redirectUrls = new RedirectUrls();
        redirectUrls.setCancelUrl(PayPalConfig.CANCEL_URL+"/"+itemId);
        redirectUrls.setReturnUrl(PayPalConfig.RETURN_URL+"/"+itemId);
        payment.setRedirectUrls(redirectUrls);
        System.out.println(">>> URLs");

        System.out.println(">>> CREATING PAYMENT...");
        // Create payment
        Payment createdPayment;
        try {
            createdPayment = payment.create(PayPalContext.context);
            //System.out.println(createdPayment.toJSON());
            Iterator links = createdPayment.getLinks().iterator();
            while (links.hasNext()) {
                Links link = (Links) links.next();
                if (link.getRel().equalsIgnoreCase("approval_url")) {
                    // REDIRECT USER TO link.getHref()
                    System.out.println(">>> CREATING PAYMENT SUCCESS!");
                    System.out.println(">>> REDIRECT TO 'APPROVAL_URL': "+ link.toJSON());
                    //TODO - return just link, instead of whole object
                    //https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/PaymentWithPayPalServlet.java
                    return link;
                }
            }
        } catch (PayPalRESTException e) {
            System.err.println(e.getDetails());
            System.out.println(">>> CREATING PAYMENT ERROR");
        }
        return null;
    }


    /**
     * When user confirms or cancels payment on URL that is generated by PayPal in 'createPayment(...)'
     * Flow:
     * 0. PayPal redirect user to our website (to the url specified in Payment object (cancel url & return url))
     * 1. Beside just redirecting to that url, there will be 2 params provided by PayPal: PayerID and paymentId
     * 2. From there we call our backend with those parameters + param from URL that has idemID to confirm(finish payment)
     * 3. We call PayPal to execute payment
     *
     * @param PayerID payer id generated by PayPal
     * @param paymentId payment id generated by PayPal
     * @return TODO - return some msg
     * */
    public void executePayment(String PayerID, String paymentId){

        /*
        req.getParameter("PayerID")
        req.getParameter("paymentId")
        */

        Payment payment = new Payment();
        payment.setId(paymentId);

        PaymentExecution paymentExecution = new PaymentExecution();
        paymentExecution.setPayerId(PayerID);
        try {
            Payment createdPayment = payment.execute(PayPalContext.context, paymentExecution);
            System.out.println(createdPayment.toJSON());

        } catch (PayPalRESTException e) {
            System.err.println(e.getDetails());
        }

        //TODO - in rest/serviec do this: conect paymentID with item that is bought
        // check 1: if item has payment id
        // check 2: get payment info from paumetID and compare it with item
        // then: save payment id inside item

    }





    public void createCreditCardPayment(){

        //TODO - credit card payment

    }




}
